# Generated by Django 3.1.2 on 2020-10-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_place_times_visited'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.RemoveField(
            model_name='place',
            name='date_visited',
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(default='Sample Place', max_length=255, unique=True),
        ),
    ]
